#!/bin/sh
set -e

AMIX_VIMRC_PATH=${AMIX_VIMRC_PATH:-/usr/local/vim_runtime}
AMIX_VIMRC_VERSION=${AMIX_VIMRC_VERSION:-master}

cd /root

echo "Installing git, vim and amix/vimrc"

apt-get update && apt-get install -y --no-install-recommends \
  ca-certificates \
  git \
  vim \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /tmp/* /var/tmp/*

git clone https://github.com/amix/vimrc.git "${AMIX_VIMRC_PATH}" \
  && ( \
  cd "${AMIX_VIMRC_PATH}" \
  && git checkout -b tmp "${AMIX_VIMRC_VERSION}" \
  && rm -rf .git \
  )

cat > /root/.vimrc \
<< EOF
" DO NOT EDIT THIS FILE
" Add your own customizations in ${AMIX_VIMRC_PATH}/my_configs.vim
set runtimepath+=${AMIX_VIMRC_PATH}
source ${AMIX_VIMRC_PATH}/vimrcs/basic.vim
source ${AMIX_VIMRC_PATH}/vimrcs/filetypes.vim
source ${AMIX_VIMRC_PATH}/vimrcs/plugins_config.vim
source ${AMIX_VIMRC_PATH}/vimrcs/extended.vim
try
  source ${AMIX_VIMRC_PATH}/my_configs.vim
catch
endtry
EOF